spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:


  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true

    hibernate:
      ddl-auto: create


  profiles:
    include: jwt
file:
  dir: C:\files\
#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug
#
#      hibernate:
#        SQL: debug
#
#    springmvc:
#      board:info